//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SNOTELCatalogModel", "FK_Variables_Units", "Units", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UpdateSnotel.Units), "Variables", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UpdateSnotel.Variables))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SNOTELCatalogModel", "FK_Variables_Units1", "Units", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(UpdateSnotel.Units), "Variables", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UpdateSnotel.Variables))]

// Original file name:
// Generation date: 6/28/2010 2:44:35 PM
namespace UpdateSnotel
{
    
    /// <summary>
    /// There are no comments for SNOTELEntities in the schema.
    /// </summary>
    public partial class SNOTELEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SNOTELEntities object using the connection string found in the 'SNOTELEntities' section of the application configuration file.
        /// </summary>
        public SNOTELEntities() : 
                base("name=SNOTELEntities", "SNOTELEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SNOTELEntities object.
        /// </summary>
        public SNOTELEntities(string connectionString) : 
                base(connectionString, "SNOTELEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SNOTELEntities object.
        /// </summary>
        public SNOTELEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SNOTELEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Methods in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Methods> Methods
        {
            get
            {
                if ((this._Methods == null))
                {
                    this._Methods = base.CreateQuery<Methods>("[Methods]");
                }
                return this._Methods;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Methods> _Methods;
        /// <summary>
        /// There are no comments for SeriesCatalog in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<SeriesCatalog> SeriesCatalog
        {
            get
            {
                if ((this._SeriesCatalog == null))
                {
                    this._SeriesCatalog = base.CreateQuery<SeriesCatalog>("[SeriesCatalog]");
                }
                return this._SeriesCatalog;
            }
        }
        private global::System.Data.Objects.ObjectQuery<SeriesCatalog> _SeriesCatalog;
        /// <summary>
        /// There are no comments for Sites in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Sites> Sites
        {
            get
            {
                if ((this._Sites == null))
                {
                    this._Sites = base.CreateQuery<Sites>("[Sites]");
                }
                return this._Sites;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Sites> _Sites;
        /// <summary>
        /// There are no comments for Sources in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Sources> Sources
        {
            get
            {
                if ((this._Sources == null))
                {
                    this._Sources = base.CreateQuery<Sources>("[Sources]");
                }
                return this._Sources;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Sources> _Sources;
        /// <summary>
        /// There are no comments for Units in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Units> Units
        {
            get
            {
                if ((this._Units == null))
                {
                    this._Units = base.CreateQuery<Units>("[Units]");
                }
                return this._Units;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Units> _Units;
        /// <summary>
        /// There are no comments for Variables in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Variables> Variables
        {
            get
            {
                if ((this._Variables == null))
                {
                    this._Variables = base.CreateQuery<Variables>("[Variables]");
                }
                return this._Variables;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Variables> _Variables;
        /// <summary>
        /// There are no comments for Methods in the schema.
        /// </summary>
        public void AddToMethods(Methods methods)
        {
            base.AddObject("Methods", methods);
        }
        /// <summary>
        /// There are no comments for SeriesCatalog in the schema.
        /// </summary>
        public void AddToSeriesCatalog(SeriesCatalog seriesCatalog)
        {
            base.AddObject("SeriesCatalog", seriesCatalog);
        }
        /// <summary>
        /// There are no comments for Sites in the schema.
        /// </summary>
        public void AddToSites(Sites sites)
        {
            base.AddObject("Sites", sites);
        }
        /// <summary>
        /// There are no comments for Sources in the schema.
        /// </summary>
        public void AddToSources(Sources sources)
        {
            base.AddObject("Sources", sources);
        }
        /// <summary>
        /// There are no comments for Units in the schema.
        /// </summary>
        public void AddToUnits(Units units)
        {
            base.AddObject("Units", units);
        }
        /// <summary>
        /// There are no comments for Variables in the schema.
        /// </summary>
        public void AddToVariables(Variables variables)
        {
            base.AddObject("Variables", variables);
        }
    }
    /// <summary>
    /// There are no comments for SNOTELCatalogModel.Methods in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MethodID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SNOTELCatalogModel", Name="Methods")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Methods : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Methods object.
        /// </summary>
        /// <param name="methodID">Initial value of MethodID.</param>
        /// <param name="methodDescription">Initial value of MethodDescription.</param>
        public static Methods CreateMethods(int methodID, string methodDescription)
        {
            Methods methods = new Methods();
            methods.MethodID = methodID;
            methods.MethodDescription = methodDescription;
            return methods;
        }
        /// <summary>
        /// There are no comments for Property MethodID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MethodID
        {
            get
            {
                return this._MethodID;
            }
            set
            {
                this.OnMethodIDChanging(value);
                this.ReportPropertyChanging("MethodID");
                this._MethodID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MethodID");
                this.OnMethodIDChanged();
            }
        }
        private int _MethodID;
        partial void OnMethodIDChanging(int value);
        partial void OnMethodIDChanged();
        /// <summary>
        /// There are no comments for Property MethodDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodDescription
        {
            get
            {
                return this._MethodDescription;
            }
            set
            {
                this.OnMethodDescriptionChanging(value);
                this.ReportPropertyChanging("MethodDescription");
                this._MethodDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MethodDescription");
                this.OnMethodDescriptionChanged();
            }
        }
        private string _MethodDescription;
        partial void OnMethodDescriptionChanging(string value);
        partial void OnMethodDescriptionChanged();
        /// <summary>
        /// There are no comments for Property MethodLink in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodLink
        {
            get
            {
                return this._MethodLink;
            }
            set
            {
                this.OnMethodLinkChanging(value);
                this.ReportPropertyChanging("MethodLink");
                this._MethodLink = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MethodLink");
                this.OnMethodLinkChanged();
            }
        }
        private string _MethodLink;
        partial void OnMethodLinkChanging(string value);
        partial void OnMethodLinkChanged();
    }
    /// <summary>
    /// There are no comments for SNOTELCatalogModel.SeriesCatalog in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SeriesID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SNOTELCatalogModel", Name="SeriesCatalog")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SeriesCatalog : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SeriesCatalog object.
        /// </summary>
        /// <param name="seriesID">Initial value of SeriesID.</param>
        public static SeriesCatalog CreateSeriesCatalog(int seriesID)
        {
            SeriesCatalog seriesCatalog = new SeriesCatalog();
            seriesCatalog.SeriesID = seriesID;
            return seriesCatalog;
        }
        /// <summary>
        /// There are no comments for Property SeriesID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SeriesID
        {
            get
            {
                return this._SeriesID;
            }
            set
            {
                this.OnSeriesIDChanging(value);
                this.ReportPropertyChanging("SeriesID");
                this._SeriesID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SeriesID");
                this.OnSeriesIDChanged();
            }
        }
        private int _SeriesID;
        partial void OnSeriesIDChanging(int value);
        partial void OnSeriesIDChanged();
        /// <summary>
        /// There are no comments for Property SiteID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SiteID
        {
            get
            {
                return this._SiteID;
            }
            set
            {
                this.OnSiteIDChanging(value);
                this.ReportPropertyChanging("SiteID");
                this._SiteID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SiteID");
                this.OnSiteIDChanged();
            }
        }
        private global::System.Nullable<int> _SiteID;
        partial void OnSiteIDChanging(global::System.Nullable<int> value);
        partial void OnSiteIDChanged();
        /// <summary>
        /// There are no comments for Property SiteCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteCode
        {
            get
            {
                return this._SiteCode;
            }
            set
            {
                this.OnSiteCodeChanging(value);
                this.ReportPropertyChanging("SiteCode");
                this._SiteCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SiteCode");
                this.OnSiteCodeChanged();
            }
        }
        private string _SiteCode;
        partial void OnSiteCodeChanging(string value);
        partial void OnSiteCodeChanged();
        /// <summary>
        /// There are no comments for Property SiteName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName
        {
            get
            {
                return this._SiteName;
            }
            set
            {
                this.OnSiteNameChanging(value);
                this.ReportPropertyChanging("SiteName");
                this._SiteName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SiteName");
                this.OnSiteNameChanged();
            }
        }
        private string _SiteName;
        partial void OnSiteNameChanging(string value);
        partial void OnSiteNameChanged();
        /// <summary>
        /// There are no comments for Property VariableID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> VariableID
        {
            get
            {
                return this._VariableID;
            }
            set
            {
                this.OnVariableIDChanging(value);
                this.ReportPropertyChanging("VariableID");
                this._VariableID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("VariableID");
                this.OnVariableIDChanged();
            }
        }
        private global::System.Nullable<int> _VariableID;
        partial void OnVariableIDChanging(global::System.Nullable<int> value);
        partial void OnVariableIDChanged();
        /// <summary>
        /// There are no comments for Property VariableCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VariableCode
        {
            get
            {
                return this._VariableCode;
            }
            set
            {
                this.OnVariableCodeChanging(value);
                this.ReportPropertyChanging("VariableCode");
                this._VariableCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("VariableCode");
                this.OnVariableCodeChanged();
            }
        }
        private string _VariableCode;
        partial void OnVariableCodeChanging(string value);
        partial void OnVariableCodeChanged();
        /// <summary>
        /// There are no comments for Property VariableName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VariableName
        {
            get
            {
                return this._VariableName;
            }
            set
            {
                this.OnVariableNameChanging(value);
                this.ReportPropertyChanging("VariableName");
                this._VariableName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("VariableName");
                this.OnVariableNameChanged();
            }
        }
        private string _VariableName;
        partial void OnVariableNameChanging(string value);
        partial void OnVariableNameChanged();
        /// <summary>
        /// There are no comments for Property Speciation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Speciation
        {
            get
            {
                return this._Speciation;
            }
            set
            {
                this.OnSpeciationChanging(value);
                this.ReportPropertyChanging("Speciation");
                this._Speciation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Speciation");
                this.OnSpeciationChanged();
            }
        }
        private string _Speciation;
        partial void OnSpeciationChanging(string value);
        partial void OnSpeciationChanged();
        /// <summary>
        /// There are no comments for Property VariableUnitsID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> VariableUnitsID
        {
            get
            {
                return this._VariableUnitsID;
            }
            set
            {
                this.OnVariableUnitsIDChanging(value);
                this.ReportPropertyChanging("VariableUnitsID");
                this._VariableUnitsID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("VariableUnitsID");
                this.OnVariableUnitsIDChanged();
            }
        }
        private global::System.Nullable<int> _VariableUnitsID;
        partial void OnVariableUnitsIDChanging(global::System.Nullable<int> value);
        partial void OnVariableUnitsIDChanged();
        /// <summary>
        /// There are no comments for Property VariableUnitsName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VariableUnitsName
        {
            get
            {
                return this._VariableUnitsName;
            }
            set
            {
                this.OnVariableUnitsNameChanging(value);
                this.ReportPropertyChanging("VariableUnitsName");
                this._VariableUnitsName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("VariableUnitsName");
                this.OnVariableUnitsNameChanged();
            }
        }
        private string _VariableUnitsName;
        partial void OnVariableUnitsNameChanging(string value);
        partial void OnVariableUnitsNameChanged();
        /// <summary>
        /// There are no comments for Property SampleMedium in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SampleMedium
        {
            get
            {
                return this._SampleMedium;
            }
            set
            {
                this.OnSampleMediumChanging(value);
                this.ReportPropertyChanging("SampleMedium");
                this._SampleMedium = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SampleMedium");
                this.OnSampleMediumChanged();
            }
        }
        private string _SampleMedium;
        partial void OnSampleMediumChanging(string value);
        partial void OnSampleMediumChanged();
        /// <summary>
        /// There are no comments for Property ValueType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueType
        {
            get
            {
                return this._ValueType;
            }
            set
            {
                this.OnValueTypeChanging(value);
                this.ReportPropertyChanging("ValueType");
                this._ValueType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ValueType");
                this.OnValueTypeChanged();
            }
        }
        private string _ValueType;
        partial void OnValueTypeChanging(string value);
        partial void OnValueTypeChanged();
        /// <summary>
        /// There are no comments for Property TimeSupport in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> TimeSupport
        {
            get
            {
                return this._TimeSupport;
            }
            set
            {
                this.OnTimeSupportChanging(value);
                this.ReportPropertyChanging("TimeSupport");
                this._TimeSupport = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TimeSupport");
                this.OnTimeSupportChanged();
            }
        }
        private global::System.Nullable<double> _TimeSupport;
        partial void OnTimeSupportChanging(global::System.Nullable<double> value);
        partial void OnTimeSupportChanged();
        /// <summary>
        /// There are no comments for Property TimeUnitsID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> TimeUnitsID
        {
            get
            {
                return this._TimeUnitsID;
            }
            set
            {
                this.OnTimeUnitsIDChanging(value);
                this.ReportPropertyChanging("TimeUnitsID");
                this._TimeUnitsID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TimeUnitsID");
                this.OnTimeUnitsIDChanged();
            }
        }
        private global::System.Nullable<int> _TimeUnitsID;
        partial void OnTimeUnitsIDChanging(global::System.Nullable<int> value);
        partial void OnTimeUnitsIDChanged();
        /// <summary>
        /// There are no comments for Property TimeUnitsName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeUnitsName
        {
            get
            {
                return this._TimeUnitsName;
            }
            set
            {
                this.OnTimeUnitsNameChanging(value);
                this.ReportPropertyChanging("TimeUnitsName");
                this._TimeUnitsName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("TimeUnitsName");
                this.OnTimeUnitsNameChanged();
            }
        }
        private string _TimeUnitsName;
        partial void OnTimeUnitsNameChanging(string value);
        partial void OnTimeUnitsNameChanged();
        /// <summary>
        /// There are no comments for Property DataType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType
        {
            get
            {
                return this._DataType;
            }
            set
            {
                this.OnDataTypeChanging(value);
                this.ReportPropertyChanging("DataType");
                this._DataType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DataType");
                this.OnDataTypeChanged();
            }
        }
        private string _DataType;
        partial void OnDataTypeChanging(string value);
        partial void OnDataTypeChanged();
        /// <summary>
        /// There are no comments for Property GeneralCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralCategory
        {
            get
            {
                return this._GeneralCategory;
            }
            set
            {
                this.OnGeneralCategoryChanging(value);
                this.ReportPropertyChanging("GeneralCategory");
                this._GeneralCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GeneralCategory");
                this.OnGeneralCategoryChanged();
            }
        }
        private string _GeneralCategory;
        partial void OnGeneralCategoryChanging(string value);
        partial void OnGeneralCategoryChanged();
        /// <summary>
        /// There are no comments for Property MethodID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> MethodID
        {
            get
            {
                return this._MethodID;
            }
            set
            {
                this.OnMethodIDChanging(value);
                this.ReportPropertyChanging("MethodID");
                this._MethodID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MethodID");
                this.OnMethodIDChanged();
            }
        }
        private global::System.Nullable<int> _MethodID;
        partial void OnMethodIDChanging(global::System.Nullable<int> value);
        partial void OnMethodIDChanged();
        /// <summary>
        /// There are no comments for Property MethodDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodDescription
        {
            get
            {
                return this._MethodDescription;
            }
            set
            {
                this.OnMethodDescriptionChanging(value);
                this.ReportPropertyChanging("MethodDescription");
                this._MethodDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("MethodDescription");
                this.OnMethodDescriptionChanged();
            }
        }
        private string _MethodDescription;
        partial void OnMethodDescriptionChanging(string value);
        partial void OnMethodDescriptionChanged();
        /// <summary>
        /// There are no comments for Property SourceID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SourceID
        {
            get
            {
                return this._SourceID;
            }
            set
            {
                this.OnSourceIDChanging(value);
                this.ReportPropertyChanging("SourceID");
                this._SourceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SourceID");
                this.OnSourceIDChanged();
            }
        }
        private global::System.Nullable<int> _SourceID;
        partial void OnSourceIDChanging(global::System.Nullable<int> value);
        partial void OnSourceIDChanged();
        /// <summary>
        /// There are no comments for Property Organization in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization
        {
            get
            {
                return this._Organization;
            }
            set
            {
                this.OnOrganizationChanging(value);
                this.ReportPropertyChanging("Organization");
                this._Organization = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Organization");
                this.OnOrganizationChanged();
            }
        }
        private string _Organization;
        partial void OnOrganizationChanging(string value);
        partial void OnOrganizationChanged();
        /// <summary>
        /// There are no comments for Property SourceDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceDescription
        {
            get
            {
                return this._SourceDescription;
            }
            set
            {
                this.OnSourceDescriptionChanging(value);
                this.ReportPropertyChanging("SourceDescription");
                this._SourceDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SourceDescription");
                this.OnSourceDescriptionChanged();
            }
        }
        private string _SourceDescription;
        partial void OnSourceDescriptionChanging(string value);
        partial void OnSourceDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Citation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Citation
        {
            get
            {
                return this._Citation;
            }
            set
            {
                this.OnCitationChanging(value);
                this.ReportPropertyChanging("Citation");
                this._Citation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Citation");
                this.OnCitationChanged();
            }
        }
        private string _Citation;
        partial void OnCitationChanging(string value);
        partial void OnCitationChanged();
        /// <summary>
        /// There are no comments for Property QualityControlLevelID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> QualityControlLevelID
        {
            get
            {
                return this._QualityControlLevelID;
            }
            set
            {
                this.OnQualityControlLevelIDChanging(value);
                this.ReportPropertyChanging("QualityControlLevelID");
                this._QualityControlLevelID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("QualityControlLevelID");
                this.OnQualityControlLevelIDChanged();
            }
        }
        private global::System.Nullable<int> _QualityControlLevelID;
        partial void OnQualityControlLevelIDChanging(global::System.Nullable<int> value);
        partial void OnQualityControlLevelIDChanged();
        /// <summary>
        /// There are no comments for Property QualityControlLevelCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string QualityControlLevelCode
        {
            get
            {
                return this._QualityControlLevelCode;
            }
            set
            {
                this.OnQualityControlLevelCodeChanging(value);
                this.ReportPropertyChanging("QualityControlLevelCode");
                this._QualityControlLevelCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("QualityControlLevelCode");
                this.OnQualityControlLevelCodeChanged();
            }
        }
        private string _QualityControlLevelCode;
        partial void OnQualityControlLevelCodeChanging(string value);
        partial void OnQualityControlLevelCodeChanged();
        /// <summary>
        /// There are no comments for Property BeginDateTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> BeginDateTime
        {
            get
            {
                return this._BeginDateTime;
            }
            set
            {
                this.OnBeginDateTimeChanging(value);
                this.ReportPropertyChanging("BeginDateTime");
                this._BeginDateTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BeginDateTime");
                this.OnBeginDateTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _BeginDateTime;
        partial void OnBeginDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnBeginDateTimeChanged();
        /// <summary>
        /// There are no comments for Property EndDateTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> EndDateTime
        {
            get
            {
                return this._EndDateTime;
            }
            set
            {
                this.OnEndDateTimeChanging(value);
                this.ReportPropertyChanging("EndDateTime");
                this._EndDateTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndDateTime");
                this.OnEndDateTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _EndDateTime;
        partial void OnEndDateTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndDateTimeChanged();
        /// <summary>
        /// There are no comments for Property BeginDateTimeUTC in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> BeginDateTimeUTC
        {
            get
            {
                return this._BeginDateTimeUTC;
            }
            set
            {
                this.OnBeginDateTimeUTCChanging(value);
                this.ReportPropertyChanging("BeginDateTimeUTC");
                this._BeginDateTimeUTC = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("BeginDateTimeUTC");
                this.OnBeginDateTimeUTCChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _BeginDateTimeUTC;
        partial void OnBeginDateTimeUTCChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnBeginDateTimeUTCChanged();
        /// <summary>
        /// There are no comments for Property EndDateTimeUTC in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> EndDateTimeUTC
        {
            get
            {
                return this._EndDateTimeUTC;
            }
            set
            {
                this.OnEndDateTimeUTCChanging(value);
                this.ReportPropertyChanging("EndDateTimeUTC");
                this._EndDateTimeUTC = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EndDateTimeUTC");
                this.OnEndDateTimeUTCChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _EndDateTimeUTC;
        partial void OnEndDateTimeUTCChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEndDateTimeUTCChanged();
        /// <summary>
        /// There are no comments for Property ValueCount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ValueCount
        {
            get
            {
                return this._ValueCount;
            }
            set
            {
                this.OnValueCountChanging(value);
                this.ReportPropertyChanging("ValueCount");
                this._ValueCount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ValueCount");
                this.OnValueCountChanged();
            }
        }
        private global::System.Nullable<int> _ValueCount;
        partial void OnValueCountChanging(global::System.Nullable<int> value);
        partial void OnValueCountChanged();
    }
    /// <summary>
    /// There are no comments for SNOTELCatalogModel.Sites in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SiteID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SNOTELCatalogModel", Name="Sites")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Sites : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Sites object.
        /// </summary>
        /// <param name="siteID">Initial value of SiteID.</param>
        /// <param name="siteCode">Initial value of SiteCode.</param>
        /// <param name="siteName">Initial value of SiteName.</param>
        /// <param name="latitude">Initial value of Latitude.</param>
        /// <param name="longitude">Initial value of Longitude.</param>
        /// <param name="latLongDatumID">Initial value of LatLongDatumID.</param>
        public static Sites CreateSites(int siteID, string siteCode, string siteName, double latitude, double longitude, int latLongDatumID)
        {
            Sites sites = new Sites();
            sites.SiteID = siteID;
            sites.SiteCode = siteCode;
            sites.SiteName = siteName;
            sites.Latitude = latitude;
            sites.Longitude = longitude;
            sites.LatLongDatumID = latLongDatumID;
            return sites;
        }
        /// <summary>
        /// There are no comments for Property SiteID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteID
        {
            get
            {
                return this._SiteID;
            }
            set
            {
                this.OnSiteIDChanging(value);
                this.ReportPropertyChanging("SiteID");
                this._SiteID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SiteID");
                this.OnSiteIDChanged();
            }
        }
        private int _SiteID;
        partial void OnSiteIDChanging(int value);
        partial void OnSiteIDChanged();
        /// <summary>
        /// There are no comments for Property SiteCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteCode
        {
            get
            {
                return this._SiteCode;
            }
            set
            {
                this.OnSiteCodeChanging(value);
                this.ReportPropertyChanging("SiteCode");
                this._SiteCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SiteCode");
                this.OnSiteCodeChanged();
            }
        }
        private string _SiteCode;
        partial void OnSiteCodeChanging(string value);
        partial void OnSiteCodeChanged();
        /// <summary>
        /// There are no comments for Property SiteName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteName
        {
            get
            {
                return this._SiteName;
            }
            set
            {
                this.OnSiteNameChanging(value);
                this.ReportPropertyChanging("SiteName");
                this._SiteName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SiteName");
                this.OnSiteNameChanged();
            }
        }
        private string _SiteName;
        partial void OnSiteNameChanging(string value);
        partial void OnSiteNameChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this.ReportPropertyChanging("Latitude");
                this._Latitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Latitude");
                this.OnLatitudeChanged();
            }
        }
        private double _Latitude;
        partial void OnLatitudeChanging(double value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this.ReportPropertyChanging("Longitude");
                this._Longitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Longitude");
                this.OnLongitudeChanged();
            }
        }
        private double _Longitude;
        partial void OnLongitudeChanging(double value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// There are no comments for Property LatLongDatumID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LatLongDatumID
        {
            get
            {
                return this._LatLongDatumID;
            }
            set
            {
                this.OnLatLongDatumIDChanging(value);
                this.ReportPropertyChanging("LatLongDatumID");
                this._LatLongDatumID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LatLongDatumID");
                this.OnLatLongDatumIDChanged();
            }
        }
        private int _LatLongDatumID;
        partial void OnLatLongDatumIDChanging(int value);
        partial void OnLatLongDatumIDChanged();
        /// <summary>
        /// There are no comments for Property Elevation_m in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> Elevation_m
        {
            get
            {
                return this._Elevation_m;
            }
            set
            {
                this.OnElevation_mChanging(value);
                this.ReportPropertyChanging("Elevation_m");
                this._Elevation_m = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Elevation_m");
                this.OnElevation_mChanged();
            }
        }
        private global::System.Nullable<double> _Elevation_m;
        partial void OnElevation_mChanging(global::System.Nullable<double> value);
        partial void OnElevation_mChanged();
        /// <summary>
        /// There are no comments for Property VerticalDatum in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VerticalDatum
        {
            get
            {
                return this._VerticalDatum;
            }
            set
            {
                this.OnVerticalDatumChanging(value);
                this.ReportPropertyChanging("VerticalDatum");
                this._VerticalDatum = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("VerticalDatum");
                this.OnVerticalDatumChanged();
            }
        }
        private string _VerticalDatum;
        partial void OnVerticalDatumChanging(string value);
        partial void OnVerticalDatumChanged();
        /// <summary>
        /// There are no comments for Property LocalX in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> LocalX
        {
            get
            {
                return this._LocalX;
            }
            set
            {
                this.OnLocalXChanging(value);
                this.ReportPropertyChanging("LocalX");
                this._LocalX = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocalX");
                this.OnLocalXChanged();
            }
        }
        private global::System.Nullable<double> _LocalX;
        partial void OnLocalXChanging(global::System.Nullable<double> value);
        partial void OnLocalXChanged();
        /// <summary>
        /// There are no comments for Property LocalY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> LocalY
        {
            get
            {
                return this._LocalY;
            }
            set
            {
                this.OnLocalYChanging(value);
                this.ReportPropertyChanging("LocalY");
                this._LocalY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocalY");
                this.OnLocalYChanged();
            }
        }
        private global::System.Nullable<double> _LocalY;
        partial void OnLocalYChanging(global::System.Nullable<double> value);
        partial void OnLocalYChanged();
        /// <summary>
        /// There are no comments for Property LocalProjectionID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> LocalProjectionID
        {
            get
            {
                return this._LocalProjectionID;
            }
            set
            {
                this.OnLocalProjectionIDChanging(value);
                this.ReportPropertyChanging("LocalProjectionID");
                this._LocalProjectionID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocalProjectionID");
                this.OnLocalProjectionIDChanged();
            }
        }
        private global::System.Nullable<int> _LocalProjectionID;
        partial void OnLocalProjectionIDChanging(global::System.Nullable<int> value);
        partial void OnLocalProjectionIDChanged();
        /// <summary>
        /// There are no comments for Property PosAccuracy_m in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> PosAccuracy_m
        {
            get
            {
                return this._PosAccuracy_m;
            }
            set
            {
                this.OnPosAccuracy_mChanging(value);
                this.ReportPropertyChanging("PosAccuracy_m");
                this._PosAccuracy_m = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PosAccuracy_m");
                this.OnPosAccuracy_mChanged();
            }
        }
        private global::System.Nullable<double> _PosAccuracy_m;
        partial void OnPosAccuracy_mChanging(global::System.Nullable<double> value);
        partial void OnPosAccuracy_mChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this.ReportPropertyChanging("State");
                this._State = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("State");
                this.OnStateChanged();
            }
        }
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property County in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string County
        {
            get
            {
                return this._County;
            }
            set
            {
                this.OnCountyChanging(value);
                this.ReportPropertyChanging("County");
                this._County = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("County");
                this.OnCountyChanged();
            }
        }
        private string _County;
        partial void OnCountyChanging(string value);
        partial void OnCountyChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this.ReportPropertyChanging("Comments");
                this._Comments = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Comments");
                this.OnCommentsChanged();
            }
        }
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property TimeZone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> TimeZone
        {
            get
            {
                return this._TimeZone;
            }
            set
            {
                this.OnTimeZoneChanging(value);
                this.ReportPropertyChanging("TimeZone");
                this._TimeZone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TimeZone");
                this.OnTimeZoneChanged();
            }
        }
        private global::System.Nullable<int> _TimeZone;
        partial void OnTimeZoneChanging(global::System.Nullable<int> value);
        partial void OnTimeZoneChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
    }
    /// <summary>
    /// There are no comments for SNOTELCatalogModel.Sources in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SourceID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SNOTELCatalogModel", Name="Sources")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Sources : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Sources object.
        /// </summary>
        /// <param name="sourceID">Initial value of SourceID.</param>
        /// <param name="organization">Initial value of Organization.</param>
        /// <param name="sourceDescription">Initial value of SourceDescription.</param>
        /// <param name="contactName">Initial value of ContactName.</param>
        /// <param name="phone">Initial value of Phone.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="city">Initial value of City.</param>
        /// <param name="state">Initial value of State.</param>
        /// <param name="zipCode">Initial value of ZipCode.</param>
        /// <param name="citation">Initial value of Citation.</param>
        /// <param name="metadataID">Initial value of MetadataID.</param>
        public static Sources CreateSources(int sourceID, string organization, string sourceDescription, string contactName, string phone, string email, string address, string city, string state, string zipCode, string citation, int metadataID)
        {
            Sources sources = new Sources();
            sources.SourceID = sourceID;
            sources.Organization = organization;
            sources.SourceDescription = sourceDescription;
            sources.ContactName = contactName;
            sources.Phone = phone;
            sources.Email = email;
            sources.Address = address;
            sources.City = city;
            sources.State = state;
            sources.ZipCode = zipCode;
            sources.Citation = citation;
            sources.MetadataID = metadataID;
            return sources;
        }
        /// <summary>
        /// There are no comments for Property SourceID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SourceID
        {
            get
            {
                return this._SourceID;
            }
            set
            {
                this.OnSourceIDChanging(value);
                this.ReportPropertyChanging("SourceID");
                this._SourceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SourceID");
                this.OnSourceIDChanged();
            }
        }
        private int _SourceID;
        partial void OnSourceIDChanging(int value);
        partial void OnSourceIDChanged();
        /// <summary>
        /// There are no comments for Property Organization in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization
        {
            get
            {
                return this._Organization;
            }
            set
            {
                this.OnOrganizationChanging(value);
                this.ReportPropertyChanging("Organization");
                this._Organization = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Organization");
                this.OnOrganizationChanged();
            }
        }
        private string _Organization;
        partial void OnOrganizationChanging(string value);
        partial void OnOrganizationChanged();
        /// <summary>
        /// There are no comments for Property SourceDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceDescription
        {
            get
            {
                return this._SourceDescription;
            }
            set
            {
                this.OnSourceDescriptionChanging(value);
                this.ReportPropertyChanging("SourceDescription");
                this._SourceDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SourceDescription");
                this.OnSourceDescriptionChanged();
            }
        }
        private string _SourceDescription;
        partial void OnSourceDescriptionChanging(string value);
        partial void OnSourceDescriptionChanged();
        /// <summary>
        /// There are no comments for Property SourceLink in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceLink
        {
            get
            {
                return this._SourceLink;
            }
            set
            {
                this.OnSourceLinkChanging(value);
                this.ReportPropertyChanging("SourceLink");
                this._SourceLink = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SourceLink");
                this.OnSourceLinkChanged();
            }
        }
        private string _SourceLink;
        partial void OnSourceLinkChanging(string value);
        partial void OnSourceLinkChanged();
        /// <summary>
        /// There are no comments for Property ContactName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this._ContactName;
            }
            set
            {
                this.OnContactNameChanging(value);
                this.ReportPropertyChanging("ContactName");
                this._ContactName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ContactName");
                this.OnContactNameChanged();
            }
        }
        private string _ContactName;
        partial void OnContactNameChanging(string value);
        partial void OnContactNameChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this.ReportPropertyChanging("Phone");
                this._Phone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Phone");
                this.OnPhoneChanged();
            }
        }
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this.ReportPropertyChanging("Address");
                this._Address = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Address");
                this.OnAddressChanged();
            }
        }
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this.ReportPropertyChanging("State");
                this._State = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("State");
                this.OnStateChanged();
            }
        }
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property ZipCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this._ZipCode;
            }
            set
            {
                this.OnZipCodeChanging(value);
                this.ReportPropertyChanging("ZipCode");
                this._ZipCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ZipCode");
                this.OnZipCodeChanged();
            }
        }
        private string _ZipCode;
        partial void OnZipCodeChanging(string value);
        partial void OnZipCodeChanged();
        /// <summary>
        /// There are no comments for Property Citation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Citation
        {
            get
            {
                return this._Citation;
            }
            set
            {
                this.OnCitationChanging(value);
                this.ReportPropertyChanging("Citation");
                this._Citation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Citation");
                this.OnCitationChanged();
            }
        }
        private string _Citation;
        partial void OnCitationChanging(string value);
        partial void OnCitationChanged();
        /// <summary>
        /// There are no comments for Property MetadataID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MetadataID
        {
            get
            {
                return this._MetadataID;
            }
            set
            {
                this.OnMetadataIDChanging(value);
                this.ReportPropertyChanging("MetadataID");
                this._MetadataID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MetadataID");
                this.OnMetadataIDChanged();
            }
        }
        private int _MetadataID;
        partial void OnMetadataIDChanging(int value);
        partial void OnMetadataIDChanged();
    }
    /// <summary>
    /// There are no comments for SNOTELCatalogModel.Units in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UnitsID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SNOTELCatalogModel", Name="Units")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Units : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Units object.
        /// </summary>
        /// <param name="unitsID">Initial value of UnitsID.</param>
        /// <param name="unitsName">Initial value of UnitsName.</param>
        /// <param name="unitsType">Initial value of UnitsType.</param>
        /// <param name="unitsAbbreviation">Initial value of UnitsAbbreviation.</param>
        public static Units CreateUnits(int unitsID, string unitsName, string unitsType, string unitsAbbreviation)
        {
            Units units = new Units();
            units.UnitsID = unitsID;
            units.UnitsName = unitsName;
            units.UnitsType = unitsType;
            units.UnitsAbbreviation = unitsAbbreviation;
            return units;
        }
        /// <summary>
        /// There are no comments for Property UnitsID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitsID
        {
            get
            {
                return this._UnitsID;
            }
            set
            {
                this.OnUnitsIDChanging(value);
                this.ReportPropertyChanging("UnitsID");
                this._UnitsID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UnitsID");
                this.OnUnitsIDChanged();
            }
        }
        private int _UnitsID;
        partial void OnUnitsIDChanging(int value);
        partial void OnUnitsIDChanged();
        /// <summary>
        /// There are no comments for Property UnitsName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitsName
        {
            get
            {
                return this._UnitsName;
            }
            set
            {
                this.OnUnitsNameChanging(value);
                this.ReportPropertyChanging("UnitsName");
                this._UnitsName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UnitsName");
                this.OnUnitsNameChanged();
            }
        }
        private string _UnitsName;
        partial void OnUnitsNameChanging(string value);
        partial void OnUnitsNameChanged();
        /// <summary>
        /// There are no comments for Property UnitsType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitsType
        {
            get
            {
                return this._UnitsType;
            }
            set
            {
                this.OnUnitsTypeChanging(value);
                this.ReportPropertyChanging("UnitsType");
                this._UnitsType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UnitsType");
                this.OnUnitsTypeChanged();
            }
        }
        private string _UnitsType;
        partial void OnUnitsTypeChanging(string value);
        partial void OnUnitsTypeChanged();
        /// <summary>
        /// There are no comments for Property UnitsAbbreviation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitsAbbreviation
        {
            get
            {
                return this._UnitsAbbreviation;
            }
            set
            {
                this.OnUnitsAbbreviationChanging(value);
                this.ReportPropertyChanging("UnitsAbbreviation");
                this._UnitsAbbreviation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UnitsAbbreviation");
                this.OnUnitsAbbreviationChanged();
            }
        }
        private string _UnitsAbbreviation;
        partial void OnUnitsAbbreviationChanging(string value);
        partial void OnUnitsAbbreviationChanged();
        /// <summary>
        /// There are no comments for Variables in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SNOTELCatalogModel", "FK_Variables_Units", "Variables")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Variables> Variables
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Variables>("SNOTELCatalogModel.FK_Variables_Units", "Variables");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Variables>("SNOTELCatalogModel.FK_Variables_Units", "Variables", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Variables1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SNOTELCatalogModel", "FK_Variables_Units1", "Variables")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Variables> Variables1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Variables>("SNOTELCatalogModel.FK_Variables_Units1", "Variables");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Variables>("SNOTELCatalogModel.FK_Variables_Units1", "Variables", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SNOTELCatalogModel.Variables in the schema.
    /// </summary>
    /// <KeyProperties>
    /// VariableID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SNOTELCatalogModel", Name="Variables")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Variables : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Variables object.
        /// </summary>
        /// <param name="variableID">Initial value of VariableID.</param>
        /// <param name="variableCode">Initial value of VariableCode.</param>
        /// <param name="variableName">Initial value of VariableName.</param>
        /// <param name="speciation">Initial value of Speciation.</param>
        /// <param name="sampleMedium">Initial value of SampleMedium.</param>
        /// <param name="valueType">Initial value of ValueType.</param>
        /// <param name="isRegular">Initial value of IsRegular.</param>
        /// <param name="timeSupport">Initial value of TimeSupport.</param>
        /// <param name="dataType">Initial value of DataType.</param>
        /// <param name="generalCategory">Initial value of GeneralCategory.</param>
        /// <param name="noDataValue">Initial value of NoDataValue.</param>
        public static Variables CreateVariables(int variableID, string variableCode, string variableName, string speciation, string sampleMedium, string valueType, bool isRegular, double timeSupport, string dataType, string generalCategory, double noDataValue)
        {
            Variables variables = new Variables();
            variables.VariableID = variableID;
            variables.VariableCode = variableCode;
            variables.VariableName = variableName;
            variables.Speciation = speciation;
            variables.SampleMedium = sampleMedium;
            variables.ValueType = valueType;
            variables.IsRegular = isRegular;
            variables.TimeSupport = timeSupport;
            variables.DataType = dataType;
            variables.GeneralCategory = generalCategory;
            variables.NoDataValue = noDataValue;
            return variables;
        }
        /// <summary>
        /// There are no comments for Property VariableID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int VariableID
        {
            get
            {
                return this._VariableID;
            }
            set
            {
                this.OnVariableIDChanging(value);
                this.ReportPropertyChanging("VariableID");
                this._VariableID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("VariableID");
                this.OnVariableIDChanged();
            }
        }
        private int _VariableID;
        partial void OnVariableIDChanging(int value);
        partial void OnVariableIDChanged();
        /// <summary>
        /// There are no comments for Property VariableCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VariableCode
        {
            get
            {
                return this._VariableCode;
            }
            set
            {
                this.OnVariableCodeChanging(value);
                this.ReportPropertyChanging("VariableCode");
                this._VariableCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("VariableCode");
                this.OnVariableCodeChanged();
            }
        }
        private string _VariableCode;
        partial void OnVariableCodeChanging(string value);
        partial void OnVariableCodeChanged();
        /// <summary>
        /// There are no comments for Property VariableName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string VariableName
        {
            get
            {
                return this._VariableName;
            }
            set
            {
                this.OnVariableNameChanging(value);
                this.ReportPropertyChanging("VariableName");
                this._VariableName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("VariableName");
                this.OnVariableNameChanged();
            }
        }
        private string _VariableName;
        partial void OnVariableNameChanging(string value);
        partial void OnVariableNameChanged();
        /// <summary>
        /// There are no comments for Property Speciation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Speciation
        {
            get
            {
                return this._Speciation;
            }
            set
            {
                this.OnSpeciationChanging(value);
                this.ReportPropertyChanging("Speciation");
                this._Speciation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Speciation");
                this.OnSpeciationChanged();
            }
        }
        private string _Speciation;
        partial void OnSpeciationChanging(string value);
        partial void OnSpeciationChanged();
        /// <summary>
        /// There are no comments for Property SampleMedium in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SampleMedium
        {
            get
            {
                return this._SampleMedium;
            }
            set
            {
                this.OnSampleMediumChanging(value);
                this.ReportPropertyChanging("SampleMedium");
                this._SampleMedium = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("SampleMedium");
                this.OnSampleMediumChanged();
            }
        }
        private string _SampleMedium;
        partial void OnSampleMediumChanging(string value);
        partial void OnSampleMediumChanged();
        /// <summary>
        /// There are no comments for Property ValueType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueType
        {
            get
            {
                return this._ValueType;
            }
            set
            {
                this.OnValueTypeChanging(value);
                this.ReportPropertyChanging("ValueType");
                this._ValueType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ValueType");
                this.OnValueTypeChanged();
            }
        }
        private string _ValueType;
        partial void OnValueTypeChanging(string value);
        partial void OnValueTypeChanged();
        /// <summary>
        /// There are no comments for Property IsRegular in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRegular
        {
            get
            {
                return this._IsRegular;
            }
            set
            {
                this.OnIsRegularChanging(value);
                this.ReportPropertyChanging("IsRegular");
                this._IsRegular = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsRegular");
                this.OnIsRegularChanged();
            }
        }
        private bool _IsRegular;
        partial void OnIsRegularChanging(bool value);
        partial void OnIsRegularChanged();
        /// <summary>
        /// There are no comments for Property TimeSupport in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double TimeSupport
        {
            get
            {
                return this._TimeSupport;
            }
            set
            {
                this.OnTimeSupportChanging(value);
                this.ReportPropertyChanging("TimeSupport");
                this._TimeSupport = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TimeSupport");
                this.OnTimeSupportChanged();
            }
        }
        private double _TimeSupport;
        partial void OnTimeSupportChanging(double value);
        partial void OnTimeSupportChanged();
        /// <summary>
        /// There are no comments for Property DataType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType
        {
            get
            {
                return this._DataType;
            }
            set
            {
                this.OnDataTypeChanging(value);
                this.ReportPropertyChanging("DataType");
                this._DataType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DataType");
                this.OnDataTypeChanged();
            }
        }
        private string _DataType;
        partial void OnDataTypeChanging(string value);
        partial void OnDataTypeChanged();
        /// <summary>
        /// There are no comments for Property GeneralCategory in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneralCategory
        {
            get
            {
                return this._GeneralCategory;
            }
            set
            {
                this.OnGeneralCategoryChanging(value);
                this.ReportPropertyChanging("GeneralCategory");
                this._GeneralCategory = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("GeneralCategory");
                this.OnGeneralCategoryChanged();
            }
        }
        private string _GeneralCategory;
        partial void OnGeneralCategoryChanging(string value);
        partial void OnGeneralCategoryChanged();
        /// <summary>
        /// There are no comments for Property NoDataValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double NoDataValue
        {
            get
            {
                return this._NoDataValue;
            }
            set
            {
                this.OnNoDataValueChanging(value);
                this.ReportPropertyChanging("NoDataValue");
                this._NoDataValue = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NoDataValue");
                this.OnNoDataValueChanged();
            }
        }
        private double _NoDataValue;
        partial void OnNoDataValueChanging(double value);
        partial void OnNoDataValueChanged();
        /// <summary>
        /// There are no comments for Units in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SNOTELCatalogModel", "FK_Variables_Units", "Units")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Units Units
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units", "Units").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units", "Units").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Units in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Units> UnitsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units", "Units");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units", "Units", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Units1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SNOTELCatalogModel", "FK_Variables_Units1", "Units")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Units Units1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units1", "Units").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units1", "Units").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Units1 in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Units> Units1Reference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units1", "Units");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Units>("SNOTELCatalogModel.FK_Variables_Units1", "Units", value);
                }
            }
        }
    }
}
